### ISSUE TITLE
Authentication is called twice

### ISSUE THREAD

**Issue by aapis** [aapis/evertils-common#16]
``` shell
/Users/ryanpriebe/Personal/evertils-common/lib/evertils/common/authentication.rb:59:in `call'
/Users/ryanpriebe/Personal/evertils-common/lib/evertils/common/authentication.rb:59:in `call'
```

This should probably only be called once, may be inflating the number of requests for no reason.

**Comment by aapis** [comment]
`Evertils::Common::Authentication` is now a singleton.  `Manager` instances use the `Authentication.instance` method to make API requests and all authentication functionality has been stripped from `Entity` methods.  These measures should reduce the app's rate limit impact.
