### ISSUE TITLE
Fix tag_create_test

### ISSUE THREAD

**Issue by aapis** [aapis/evertils-common#2]
``` shell
TagTest#test_tag_create:
Evernote::EDAM::Error::EDAMUserException: 
    /Library/Ruby/Gems/2.0.0/gems/evernote-thrift-1.25.2/lib/Evernote/EDAM/note_store.rb:291:in `recv_createTag'
    /Library/Ruby/Gems/2.0.0/gems/evernote-thrift-1.25.2/lib/Evernote/EDAM/note_store.rb:281:in `createTag'
    /Users/ryanpriebe/Personal/evertils-common/lib/evertils/common/authentication.rb:49:in `call'
    /Users/ryanpriebe/Personal/evertils-common/lib/evertils/common/authentication.rb:49:in `call'
    /Users/ryanpriebe/Personal/evertils-common/lib/evertils/common/entity/tag.rb:23:in `create'
    /Users/ryanpriebe/Personal/evertils-common/test/test_tag.rb:20:in `test_tag_create'
```

Not sure why it fails.

**Comment by aapis** [comment]
:+1:
